### ISSUE TITLE
imgs

### ISSUE THREAD

**Issue by glepnir** [glepnir/dotfiles#4]
![jump](https://user-images.githubusercontent.com/41671631/175304950-f4620c7a-9080-4496-b7cb-2a077ab9ecc0.gif)
![codeaction](https://user-images.githubusercontent.com/41671631/175305503-180e6b39-d162-4ef2-aa2b-9ffe309948e6.gif)
![lightbulb](https://user-images.githubusercontent.com/41671631/175305874-e95508e1-ecb9-4e5a-a664-85dfd3577ef1.gif)
![hover](https://user-images.githubusercontent.com/41671631/175306592-f0540e35-561f-418c-a41e-7df167ba9b86.gif)
![singature](https://user-images.githubusercontent.com/41671631/175306809-755c4624-a5d2-4c11-8b29-f41914f22411.gif)
![finder](https://user-images.githubusercontent.com/41671631/175307158-97f2a269-eeea-48e5-8b1e-d70123c30d77.gif)

**Comment by NikolaM-Dev** [comment]
What fonts are you using?. Zephir is looking excellent.

**Comment by glepnir** [comment]
It's operator mono lig

**Comment by glepnir** [comment]
![winbar](https://user-images.githubusercontent.com/41671631/176679585-9485676b-ddea-44ca-bc88-b0eb04d450b1.gif)
